### ISSUE TITLE
launch failed to start

### ISSUE THREAD

**Issue by bitmapbulgaria** [nishen/nginx-ad-proxy#1]
Hi!
Not working!
Any ideas, based on this log?

$ pipenv run launch
Loading .env environment variables...
[2023-08-09 09:59:13 +0300] [389489] [INFO] Starting gunicorn 21.2.0
[2023-08-09 09:59:13 +0300] [389489] [INFO] Listening at: http://127.0.0.1:9091 (389489)
[2023-08-09 09:59:13 +0300] [389489] [INFO] Using worker: sync
[2023-08-09 09:59:13 +0300] [389491] [INFO] Booting worker with pid: 389491
[2023-08-09 09:59:13 +0300] [389491] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/bitmap/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bitmap/Documents/nginx-ad-proxy-master/nginx_ad_proxy.py", line 3, in <module>
    import falcon
ModuleNotFoundError: No module named 'falcon'
[2023-08-09 09:59:13 +0300] [389491] [INFO] Worker exiting (pid: 389491)
[2023-08-09 09:59:13 +0300] [389489] [ERROR] Worker (pid:389491) exited with code 3
[2023-08-09 09:59:13 +0300] [389489] [ERROR] Shutting down: Master
[2023-08-09 09:59:13 +0300] [389489] [ERROR] Reason: Worker failed to boot.

**Comment by nishen** [comment]
Hi there,

Have you done a 'pipenv install'?

From the looks of it, the Falcon module seems to be missing...

**Comment by nishen** [comment]
Any luck?

**Comment by bitmapbulgaria** [comment]
"pipenv install" do the job! Thanks! Now I' Il have to learn how it works :)

**Comment by nishen** [comment]
Excellent!

It's not too complicated... Let me know if you've got any questions...

**Comment by bitmapbulgaria** [comment]
My goal is to have the user's $username as a header in the request and to proxy this as "X-username" variable to the backend. 
This is because I have and app, that use such header value to check is this user belong to some AD groups and make ana array with the values. In short - now My NGINX proxying the request, based on IP mapping, but this is not good enough- some user inside the AD network can sit to a workplace, authenticate with his/her own credentials, but will use this service as the main user. I don't want users to have to pass a  login page for the service, I hate this behavior, all we need is to authenticate in AD and based on this process, to have different access to services/functions/data and so on. Thanks for this repo, man. your code is the only one(at least I found), that points to this problem.
